"""empty message

Revision ID: 31af66e69c69
Revises: d665d91645b6
Create Date: 2020-11-17 11:56:11.267965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31af66e69c69'
down_revision = 'd665d91645b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('article', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'article', ['article'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'article')
    # ### end Alembic commands ###
