import os

DYNACONF_NAMESPACE = "TASK"
DEBUG = os.getenv("DEBUG") == "1"

POSTGRES_USER = "user111"
POSTGRES_PASS = "pass111"
POSTGRES_DB = "localdb"
POSTGRES_HOST = "postgres"
POSTGRES_PORT = "5432"
POSTGRES_URL = f'postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASS}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'
